#!/bin/sh
# Force wireless on
sed -i 's/wireless.radio${devidx}.disabled=1/wireless.radio${devidx}.disabled=0/g' /lib/wifi/mac80211.sh
sed -i 's/wireless.default_radio${devidx}.ssid=OpenWrt/wireless.default_radio${devidx}.ssid=ZeroWRT/g' /lib/wifi/mac80211.sh
# Soft wireless on
uci -q set wireless.@wifi-device[0].disabled=0
uci -q set wireless.default_radio0.ssid=ZeroWRT
uci commit wireless
wifi reload
exit 0