#!/usr/bin/zsh
        if [ -f "/etc/init.d/$1" ]; then
                /etc/init.d/$@
        else
                echo "Usage: service <service> [command]"
                if [ -n "$1" ]; then
                        echo "Service "'"'"$1"'"'" not found, the following services are available:"
                else
                        echo "The following services are available:"
                fi
                for F in /etc/init.d/* ; do
                        printf "%-30s\t%10s\t%10s\n"  "$F" \
                        $( $($F enabled) && echo "enabled" || echo "disabled" ) \
                        $( [ "$(ubus call service list "{ 'verbose': true, 'name': '$(basename $F)' }" \
                        | jsonfilter -q -e "@['$(basename $F)'].instances[*].running" | uniq)" = "true" ] \
                        && echo "running" || echo "stopped" )
                done;
                return 1
        fi

